/****************************************************************************
* FILE NAME:    pd_paramdef.h
****************************************************************************/
#ifndef PD_PARAMDEF_H
#define PD_PARAMDEF_H

#include "typedefs.h"

/****************************************************************************
 Please generate this file from EXCEL.
 Please do not edit.
 
 [This file was manually edited to change addresses to match pd_param.asm.]
****************************************************************************/

#define PRM_BL_MC1                              (*((UVFSHORT*)(0xF700)))
#define PAR_VER                                 (*((UVFSHORT*)(0xF702)))
#define BBC_VENDOR_ID                           (*((UVFSHORT*)(0xF704)))
#define BBC_PRODUCT_ID                          (*((UVFSHORT*)(0xF706)))
#define BBC_BCD_DEVICE                          (*((UVFSHORT*)(0xF708)))
#define BBC_OPTION                              (*((UVFCHAR*)(0xF70A)))
#define BBC_MAX_POWER                           (*((UVFCHAR*)(0xF70B)))
#define BBC_CONTAINER_UUID_0                    (*((UVFLONG*)(0xF70C)))
#define BBC_CONTAINER_UUID_1                    (*((UVFLONG*)(0xF710)))
#define BBC_CONTAINER_UUID_2                    (*((UVFLONG*)(0xF714)))
#define BBC_CONTAINER_UUID_3                    (*((UVFLONG*)(0xF718)))
#define BBC_NUM_ALT_MODE                        (*((UVFCHAR*)(0xF71C)))
#define BBC_PREFERRED_ALT_MODE                  (*((UVFCHAR*)(0xF71D)))
#define BBC_VCONN_POWER                         (*((UVFCHAR*)(0xF71E)))
#define BBC_SVID_0                              (*((UVFSHORT*)(0xF720)))
#define BBC_SVID_1                              (*((UVFSHORT*)(0xF722)))
#define BBC_SVID_2                              (*((UVFSHORT*)(0xF724)))
#define BBC_SVID_3                              (*((UVFSHORT*)(0xF726)))
#define BBC_ALT_MODE_0                          (*((UVFCHAR*)(0xF728)))
#define BBC_ALT_MODE_1                          (*((UVFCHAR*)(0xF729)))
#define BBC_ALT_MODE_2                          (*((UVFCHAR*)(0xF72A)))
#define BBC_ALT_MODE_3                          (*((UVFCHAR*)(0xF72B)))
#define BBC_ALT_MODE_VDO_0                      (*((UVFLONG*)(0xF72C)))
#define BBC_ALT_MODE_VDO_1                      (*((UVFLONG*)(0xF730)))
#define BBC_ALT_MODE_VDO_2                      (*((UVFLONG*)(0xF734)))
#define BBC_ALT_MODE_VDO_3                      (*((UVFLONG*)(0xF738)))
#define BBC_STR_DESCS_VALID                     (*((UVFSHORT*)(0xF73C)))
#define BBC_STR_AREA_00H                        (*((UVFLONG*)(0xF73E)))
#define BBC_STR_AREA_04H                        (*((UVFLONG*)(0xF742)))
#define BBC_STR_AREA_08H                        (*((UVFLONG*)(0xF746)))
#define BBC_STR_AREA_0CH                        (*((UVFLONG*)(0xF74A)))
#define BBC_STR_AREA_10H                        (*((UVFLONG*)(0xF74E)))
#define BBC_STR_AREA_14H                        (*((UVFLONG*)(0xF752)))
#define BBC_STR_AREA_18H                        (*((UVFLONG*)(0xF756)))
#define BBC_STR_AREA_1CH                        (*((UVFLONG*)(0xF75A)))
#define BBC_STR_AREA_20H                        (*((UVFLONG*)(0xF75E)))
#define BBC_STR_AREA_24H                        (*((UVFLONG*)(0xF762)))
#define BBC_STR_AREA_28H                        (*((UVFLONG*)(0xF766)))
#define BBC_STR_AREA_2CH                        (*((UVFLONG*)(0xF76A)))
#define BBC_STR_AREA_30H                        (*((UVFLONG*)(0xF76E)))
#define BBC_STR_AREA_34H                        (*((UVFLONG*)(0xF772)))
#define BBC_STR_AREA_38H                        (*((UVFLONG*)(0xF776)))
#define BBC_STR_AREA_3CH                        (*((UVFLONG*)(0xF77A)))
#define BBC_STR_AREA_40H                        (*((UVFLONG*)(0xF77E)))
#define BBC_STR_AREA_44H                        (*((UVFLONG*)(0xF782)))
#define BBC_STR_AREA_48H                        (*((UVFLONG*)(0xF786)))
#define BBC_STR_AREA_4CH                        (*((UVFLONG*)(0xF78A)))
#define BBC_STR_AREA_50H                        (*((UVFLONG*)(0xF78E)))
#define BBC_STR_AREA_54H                        (*((UVFLONG*)(0xF792)))
#define BBC_STR_AREA_58H                        (*((UVFLONG*)(0xF796)))
#define BBC_STR_AREA_5CH                        (*((UVFLONG*)(0xF79A)))
#define BBC_STR_AREA_60H                        (*((UVFLONG*)(0xF79E)))
#define BBC_STR_AREA_64H                        (*((UVFLONG*)(0xF7A2)))
#define BBC_STR_AREA_68H                        (*((UVFLONG*)(0xF7A6)))
#define BBC_STR_AREA_6CH                        (*((UVFLONG*)(0xF7AA)))
#define BBC_STR_AREA_70H                        (*((UVFLONG*)(0xF7AE)))
#define BBC_STR_AREA_74H                        (*((UVFLONG*)(0xF7B2)))
#define BBC_STR_AREA_78H                        (*((UVFLONG*)(0xF7B6)))
#define BBC_STR_AREA_7CH                        (*((UVFLONG*)(0xF7BA)))
#define BBC_STR_AREA_80H                        (*((UVFLONG*)(0xF7BE)))
#define BBC_STR_AREA_84H                        (*((UVFLONG*)(0xF7C2)))
#define BBC_STR_AREA_88H                        (*((UVFLONG*)(0xF7C6)))
#define BBC_STR_AREA_8CH                        (*((UVFLONG*)(0xF7CA)))
#define BBC_STR_AREA_90H                        (*((UVFLONG*)(0xF7CE)))
#define BBC_STR_AREA_94H                        (*((UVFLONG*)(0xF7D2)))
#define BBC_STR_AREA_98H                        (*((UVFLONG*)(0xF7D6)))
#define BBC_STR_AREA_9CH                        (*((UVFLONG*)(0xF7DA)))
#define BBC_STR_AREA_A0H                        (*((UVFLONG*)(0xF7DE)))
#define BBC_STR_AREA_A4H                        (*((UVFLONG*)(0xF7E2)))
#define BBC_STR_AREA_A8H                        (*((UVFLONG*)(0xF7E6)))
#define BBC_STR_AREA_ACH                        (*((UVFLONG*)(0xF7EA)))
#define BBC_STR_AREA_B0H                        (*((UVFLONG*)(0xF7EE)))
#define BBC_STR_AREA_B4H                        (*((UVFLONG*)(0xF7F2)))
#define BBC_STR_AREA_B8H                        (*((UVFLONG*)(0xF7F6)))
#define BBC_STR_AREA_BCH                        (*((UVFLONG*)(0xF7FA)))
#define BBC_STR_AREA_C0H                        (*((UVFLONG*)(0xF7FE)))
#define BBC_STR_AREA_C4H                        (*((UVFLONG*)(0xF802)))
#define BBC_STR_AREA_C8H                        (*((UVFLONG*)(0xF806)))
#define BBC_STR_AREA_CCH                        (*((UVFLONG*)(0xF80A)))
#define BBC_STR_AREA_D0H                        (*((UVFLONG*)(0xF80E)))
#define BBC_STR_AREA_D4H                        (*((UVFLONG*)(0xF812)))
#define BBC_STR_AREA_D8H                        (*((UVFLONG*)(0xF816)))
#define BBC_STR_AREA_DCH                        (*((UVFLONG*)(0xF81A)))
#define BBC_STR_AREA_E0H                        (*((UVFLONG*)(0xF81E)))
#define BBC_STR_AREA_E4H                        (*((UVFLONG*)(0xF822)))
#define BBC_STR_AREA_E8H                        (*((UVFLONG*)(0xF826)))
#define BBC_STR_AREA_ECH                        (*((UVFLONG*)(0xF82A)))
#define BBC_STR_AREA_F0H                        (*((UVFLONG*)(0xF82E)))
#define BBC_STR_AREA_F4H                        (*((UVFLONG*)(0xF832)))
#define BBC_STR_AREA_F8H                        (*((UVFLONG*)(0xF836)))
#define BBC_STR_AREA_FCH                        (*((UVFLONG*)(0xF83A)))
#define PRM_BL_MC2                              (*((UVFSHORT*)(0xFAFC)))
#define PARAM_CRC                               (*((UVFSHORT*)(0xFAFE)))

#endif  // #ifndef PD_PARAMDEF_H
/****************************************************************************
* FILE NAME:    pd_paramdef.h
****************************************************************************/

