/******************************************************************************/
/* DISCLAIMER                                                                 */
/* This software is supplied by Renesas Electronics Corporation and is only   */
/* intended for use with Renesas products. No other uses are authorized.This  */
/* software is owned by Renesas Electronics Corporation and is protected      */
/* under all applicable laws, including copyright laws.                       */
/* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES          */
/* REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING  */
/* BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR */
/* PURPOSE AND NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY           */
/* DISCLAIMED.                                                                */
/* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS     */
/* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE       */
/* LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL      */
/* DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS    */
/* AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.           */
/* Renesas reserves the right, without notice, to make changes to this        */
/* software and to discontinue the availability of this software.             */
/* By using this software, you agree to the additional terms and conditions   */
/* found by accessing the following link:                                     */
/* http://www.renesas.com/disclaimer                                          */
/*                                                                            */
/* Device     : RL78/R9A02G011                                                */
/* File Name  : iodefine.h                                                    */
/* Abstract   : Definition of Special Function Register (SFR)                 */
/* History    : E1.00e [Device File version]                                  */
/* Options    : -df=C:\Program Files (x86)\Renesas Electronics\CS+\CC\Device_ */
/*              Custom\RL78\Devicefile\DR9A02G011.DVF -o=D:\2019\sample_code_ */
/*              workspace\trunk\R9A02G011PDC_Lib_sample_premium\R9A02G011_251 */
/*              _2PB3\2PB3_Master\iodefine.h -f                               */
/* Date       : 2019/03/14                                                    */
/* Version    : V1.09.00.04  [df2iodef.exe version]                           */
/* This is a typical example.                                                 */
/*                                                                            */
/******************************************************************************/
#ifndef __R9A02G011IODEFINE_HEADER__
#define __R9A02G011IODEFINE_HEADER__

typedef struct
{
    unsigned char no0:1;
    unsigned char no1:1;
    unsigned char no2:1;
    unsigned char no3:1;
    unsigned char no4:1;
    unsigned char no5:1;
    unsigned char no6:1;
    unsigned char no7:1;
} __bitf_T;

typedef struct
{
    unsigned char no0:1;
    unsigned char no1:1;
    unsigned char no2:1;
    unsigned char no3:1;
    unsigned char no4:1;
    unsigned char no5:1;
    unsigned char no6:1;
    unsigned char no7:1;
    unsigned char no8:1;
    unsigned char no9:1;
    unsigned char no10:1;
    unsigned char no11:1;
    unsigned char no12:1;
    unsigned char no13:1;
    unsigned char no14:1;
    unsigned char no15:1;
} __bitf_T2;



#define ADM2          (*(volatile __near unsigned char  *)0x10)
#define ADM2_bit      (*(volatile __near __bitf_T *)0x10)
#define ADTYP         (((volatile __near __bitf_T *)0x10)->no0)
#define AWC           (((volatile __near __bitf_T *)0x10)->no2)
#define ADRCK         (((volatile __near __bitf_T *)0x10)->no3)
#define ADUL          (*(volatile __near unsigned char  *)0x11)
#define ADLL          (*(volatile __near unsigned char  *)0x12)
#define ADTES         (*(volatile __near unsigned char  *)0x13)
#define PU1           (*(volatile __near unsigned char  *)0x31)
#define PU1_bit       (*(volatile __near __bitf_T *)0x31)
#define PU2           (*(volatile __near unsigned char  *)0x32)
#define PU2_bit       (*(volatile __near __bitf_T *)0x32)
#define PU3           (*(volatile __near unsigned char  *)0x33)
#define PU3_bit       (*(volatile __near __bitf_T *)0x33)
#define PU4           (*(volatile __near unsigned char  *)0x34)
#define PU4_bit       (*(volatile __near __bitf_T *)0x34)
#define PU5           (*(volatile __near unsigned char  *)0x35)
#define PU5_bit       (*(volatile __near __bitf_T *)0x35)
#define PU6           (*(volatile __near unsigned char  *)0x36)
#define PU6_bit       (*(volatile __near __bitf_T *)0x36)
#define PU7           (*(volatile __near unsigned char  *)0x37)
#define PU7_bit       (*(volatile __near __bitf_T *)0x37)
#define PU8           (*(volatile __near unsigned char  *)0x38)
#define PU8_bit       (*(volatile __near __bitf_T *)0x38)
#define PIM1          (*(volatile __near unsigned char  *)0x41)
#define PIM1_bit      (*(volatile __near __bitf_T *)0x41)
#define PIM2          (*(volatile __near unsigned char  *)0x42)
#define PIM2_bit      (*(volatile __near __bitf_T *)0x42)
#define PIM3          (*(volatile __near unsigned char  *)0x43)
#define PIM3_bit      (*(volatile __near __bitf_T *)0x43)
#define PIM5          (*(volatile __near unsigned char  *)0x45)
#define PIM5_bit      (*(volatile __near __bitf_T *)0x45)
#define PIM6          (*(volatile __near unsigned char  *)0x46)
#define PIM6_bit      (*(volatile __near __bitf_T *)0x46)
#define PIM7          (*(volatile __near unsigned char  *)0x47)
#define PIM7_bit      (*(volatile __near __bitf_T *)0x47)
#define PIM8          (*(volatile __near unsigned char  *)0x48)
#define PIM8_bit      (*(volatile __near __bitf_T *)0x48)
#define POM1          (*(volatile __near unsigned char  *)0x51)
#define POM1_bit      (*(volatile __near __bitf_T *)0x51)
#define POM2          (*(volatile __near unsigned char  *)0x52)
#define POM2_bit      (*(volatile __near __bitf_T *)0x52)
#define POM3          (*(volatile __near unsigned char  *)0x53)
#define POM3_bit      (*(volatile __near __bitf_T *)0x53)
#define POM5          (*(volatile __near unsigned char  *)0x55)
#define POM5_bit      (*(volatile __near __bitf_T *)0x55)
#define POM6          (*(volatile __near unsigned char  *)0x56)
#define POM6_bit      (*(volatile __near __bitf_T *)0x56)
#define POM7          (*(volatile __near unsigned char  *)0x57)
#define POM7_bit      (*(volatile __near __bitf_T *)0x57)
#define POM8          (*(volatile __near unsigned char  *)0x58)
#define POM8_bit      (*(volatile __near __bitf_T *)0x58)
#define PMC2          (*(volatile __near unsigned char  *)0x62)
#define PMC2_bit      (*(volatile __near __bitf_T *)0x62)
#define NFEN0         (*(volatile __near unsigned char  *)0x70)
#define NFEN0_bit     (*(volatile __near __bitf_T *)0x70)
#define NFEN1         (*(volatile __near unsigned char  *)0x71)
#define NFEN1_bit     (*(volatile __near __bitf_T *)0x71)
#define TIS0          (*(volatile __near unsigned char  *)0x74)
#define TIS0_bit      (*(volatile __near __bitf_T *)0x74)
#define IAWCTL        (*(volatile __near unsigned char  *)0x78)
#define PMS           (*(volatile __near unsigned char  *)0x7B)
#define PMS_bit       (*(volatile __near __bitf_T *)0x7B)
#define HIOTRM        (*(volatile __near unsigned char  *)0xA0)
#define HOCODIV       (*(volatile __near unsigned char  *)0xA8)
#define FLMODE        (*(volatile __near unsigned char  *)0xAA)
#define FLMODE_bit    (*(volatile __near __bitf_T *)0xAA)
#define CFLSTOP       (((volatile __near __bitf_T *)0xAA)->no0)
#define MODE0         (((volatile __near __bitf_T *)0xAA)->no6)
#define MODE1         (((volatile __near __bitf_T *)0xAA)->no7)
#define FLMWRP        (*(volatile __near unsigned char  *)0xAB)
#define FLMWRP_bit    (*(volatile __near __bitf_T *)0xAB)
#define FLMWEN        (((volatile __near __bitf_T *)0xAB)->no0)
#define TEMPCAL0      (*(volatile __near unsigned char  *)0xAC)
#define TEMPCAL1      (*(volatile __near unsigned char  *)0xAD)
#define TEMPCAL2      (*(volatile __near unsigned char  *)0xAE)
#define TEMPCAL3      (*(volatile __near unsigned char  *)0xAF)
#define HWID          (*(volatile __near unsigned char  *)0xEF)
#define PER0          (*(volatile __near unsigned char  *)0xF0)
#define PER0_bit      (*(volatile __near __bitf_T *)0xF0)
#define TAU0EN        (((volatile __near __bitf_T *)0xF0)->no0)
#define SAU0EN        (((volatile __near __bitf_T *)0xF0)->no2)
#define IICA0EN       (((volatile __near __bitf_T *)0xF0)->no4)
#define ADCEN         (((volatile __near __bitf_T *)0xF0)->no5)
#define PRR0          (*(volatile __near unsigned char  *)0xF1)
#define PRR0_bit      (*(volatile __near __bitf_T *)0xF1)
#define TAU0RES       (((volatile __near __bitf_T *)0xF1)->no0)
#define SAU0RES       (((volatile __near __bitf_T *)0xF1)->no2)
#define IICA0RES      (((volatile __near __bitf_T *)0xF1)->no4)
#define ADCRES        (((volatile __near __bitf_T *)0xF1)->no5)
#define MOCODIV       (*(volatile __near unsigned char  *)0xF2)
#define OSMC          (*(volatile __near unsigned char  *)0xF3)
#define OSMC_bit      (*(volatile __near __bitf_T *)0xF3)
#define WUTMMCK0      (((volatile __near __bitf_T *)0xF3)->no4)
#define RTCLPC        (((volatile __near __bitf_T *)0xF3)->no7)
#define RMC           (*(volatile __near unsigned char  *)0xF4)
#define RMC_bit       (*(volatile __near __bitf_T *)0xF4)
#define WDVOL         (((volatile __near __bitf_T *)0xF4)->no7)
#define RPECTL        (*(volatile __near unsigned char  *)0xF5)
#define RPECTL_bit    (*(volatile __near __bitf_T *)0xF5)
#define RPEF          (((volatile __near __bitf_T *)0xF5)->no0)
#define RPERDIS       (((volatile __near __bitf_T *)0xF5)->no7)
#define PMMC          (*(volatile __near unsigned char  *)0xF8)
#define PMMC_bit      (*(volatile __near __bitf_T *)0xF8)
#define MCSEL         (((volatile __near __bitf_T *)0xF8)->no6)
#define PER2          (*(volatile __near unsigned char  *)0xFC)
#define PER2_bit      (*(volatile __near __bitf_T *)0xFC)
#define PDCTRLEN      (((volatile __near __bitf_T *)0xFC)->no0)
#define SMBMSTEN      (((volatile __near __bitf_T *)0xFC)->no1)
#define SMBSLVEN      (((volatile __near __bitf_T *)0xFC)->no2)
#define TCSCNTEN      (((volatile __near __bitf_T *)0xFC)->no3)
#define PDTICKEN      (((volatile __near __bitf_T *)0xFC)->no4)
#define TMKAEN        (((volatile __near __bitf_T *)0xFC)->no7)
#define PRR2          (*(volatile __near unsigned char  *)0xFD)
#define PRR2_bit      (*(volatile __near __bitf_T *)0xFD)
#define PDCTRLRES     (((volatile __near __bitf_T *)0xFD)->no0)
#define SMBMSTRES     (((volatile __near __bitf_T *)0xFD)->no1)
#define SMBSLVRES     (((volatile __near __bitf_T *)0xFD)->no2)
#define TCSCNTRES     (((volatile __near __bitf_T *)0xFD)->no3)
#define PDTICKRES     (((volatile __near __bitf_T *)0xFD)->no4)
#define TMKARES       (((volatile __near __bitf_T *)0xFD)->no7)
#define BCDADJ        (*(volatile __near unsigned char  *)0xFE)
#define SSR00         (*(volatile __near unsigned short *)0x100)
#define SSR00L        (*(volatile __near unsigned char  *)0x100)
#define SSR01         (*(volatile __near unsigned short *)0x102)
#define SSR01L        (*(volatile __near unsigned char  *)0x102)
#define SIR00         (*(volatile __near unsigned short *)0x108)
#define SIR00L        (*(volatile __near unsigned char  *)0x108)
#define SIR01         (*(volatile __near unsigned short *)0x10A)
#define SIR01L        (*(volatile __near unsigned char  *)0x10A)
#define SMR00         (*(volatile __near unsigned short *)0x110)
#define SMR01         (*(volatile __near unsigned short *)0x112)
#define SCR00         (*(volatile __near unsigned short *)0x118)
#define SCR01         (*(volatile __near unsigned short *)0x11A)
#define SE0           (*(volatile __near unsigned short *)0x120)
#define SE0L          (*(volatile __near unsigned char  *)0x120)
#define SE0L_bit      (*(volatile __near __bitf_T *)0x120)
#define SS0           (*(volatile __near unsigned short *)0x122)
#define SS0L          (*(volatile __near unsigned char  *)0x122)
#define SS0L_bit      (*(volatile __near __bitf_T *)0x122)
#define ST0           (*(volatile __near unsigned short *)0x124)
#define ST0L          (*(volatile __near unsigned char  *)0x124)
#define ST0L_bit      (*(volatile __near __bitf_T *)0x124)
#define SPS0          (*(volatile __near unsigned short *)0x126)
#define SPS0L         (*(volatile __near unsigned char  *)0x126)
#define SO0           (*(volatile __near unsigned short *)0x128)
#define SOE0          (*(volatile __near unsigned short *)0x12A)
#define SOE0L         (*(volatile __near unsigned char  *)0x12A)
#define SOE0L_bit     (*(volatile __near __bitf_T *)0x12A)
#define SOL0          (*(volatile __near unsigned short *)0x134)
#define SOL0L         (*(volatile __near unsigned char  *)0x134)
#define SSC0          (*(volatile __near unsigned short *)0x138)
#define SSC0L         (*(volatile __near unsigned char  *)0x138)
#define TCR00         (*(volatile __near unsigned short *)0x180)
#define TCR01         (*(volatile __near unsigned short *)0x182)
#define TCR02         (*(volatile __near unsigned short *)0x184)
#define TCR03         (*(volatile __near unsigned short *)0x186)
#define TMR00         (*(volatile __near unsigned short *)0x190)
#define TMR01         (*(volatile __near unsigned short *)0x192)
#define TMR02         (*(volatile __near unsigned short *)0x194)
#define TMR03         (*(volatile __near unsigned short *)0x196)
#define TSR00         (*(volatile __near unsigned short *)0x1A0)
#define TSR00L        (*(volatile __near unsigned char  *)0x1A0)
#define TSR01         (*(volatile __near unsigned short *)0x1A2)
#define TSR01L        (*(volatile __near unsigned char  *)0x1A2)
#define TSR02         (*(volatile __near unsigned short *)0x1A4)
#define TSR02L        (*(volatile __near unsigned char  *)0x1A4)
#define TSR03         (*(volatile __near unsigned short *)0x1A6)
#define TSR03L        (*(volatile __near unsigned char  *)0x1A6)
#define TE0           (*(volatile __near unsigned short *)0x1B0)
#define TE0L          (*(volatile __near unsigned char  *)0x1B0)
#define TE0L_bit      (*(volatile __near __bitf_T *)0x1B0)
#define TS0           (*(volatile __near unsigned short *)0x1B2)
#define TS0L          (*(volatile __near unsigned char  *)0x1B2)
#define TS0L_bit      (*(volatile __near __bitf_T *)0x1B2)
#define TT0           (*(volatile __near unsigned short *)0x1B4)
#define TT0L          (*(volatile __near unsigned char  *)0x1B4)
#define TT0L_bit      (*(volatile __near __bitf_T *)0x1B4)
#define TPS0          (*(volatile __near unsigned short *)0x1B6)
#define TO0           (*(volatile __near unsigned short *)0x1B8)
#define TO0L          (*(volatile __near unsigned char  *)0x1B8)
#define TOE0          (*(volatile __near unsigned short *)0x1BA)
#define TOE0L         (*(volatile __near unsigned char  *)0x1BA)
#define TOE0L_bit     (*(volatile __near __bitf_T *)0x1BA)
#define TOL0          (*(volatile __near unsigned short *)0x1BC)
#define TOL0L         (*(volatile __near unsigned char  *)0x1BC)
#define TOM0          (*(volatile __near unsigned short *)0x1BE)
#define TOM0L         (*(volatile __near unsigned char  *)0x1BE)
#define IICCTL00      (*(volatile __near unsigned char  *)0x230)
#define IICCTL00_bit  (*(volatile __near __bitf_T *)0x230)
#define SPT0          (((volatile __near __bitf_T *)0x230)->no0)
#define STT0          (((volatile __near __bitf_T *)0x230)->no1)
#define ACKE0         (((volatile __near __bitf_T *)0x230)->no2)
#define WTIM0         (((volatile __near __bitf_T *)0x230)->no3)
#define SPIE0         (((volatile __near __bitf_T *)0x230)->no4)
#define WREL0         (((volatile __near __bitf_T *)0x230)->no5)
#define LREL0         (((volatile __near __bitf_T *)0x230)->no6)
#define IICE0         (((volatile __near __bitf_T *)0x230)->no7)
#define IICCTL01      (*(volatile __near unsigned char  *)0x231)
#define IICCTL01_bit  (*(volatile __near __bitf_T *)0x231)
#define PRS0          (((volatile __near __bitf_T *)0x231)->no0)
#define DFC0          (((volatile __near __bitf_T *)0x231)->no2)
#define SMC0          (((volatile __near __bitf_T *)0x231)->no3)
#define DAD0          (((volatile __near __bitf_T *)0x231)->no4)
#define CLD0          (((volatile __near __bitf_T *)0x231)->no5)
#define WUP0          (((volatile __near __bitf_T *)0x231)->no7)
#define IICWL0        (*(volatile __near unsigned char  *)0x232)
#define IICWH0        (*(volatile __near unsigned char  *)0x233)
#define SVA0          (*(volatile __near unsigned char  *)0x234)
#define CRC0CTL       (*(volatile __near unsigned char  *)0x2F0)
#define CRC0CTL_bit   (*(volatile __near __bitf_T *)0x2F0)
#define FEA0          (((volatile __near __bitf_T *)0x2F0)->no0)
#define FEA1          (((volatile __near __bitf_T *)0x2F0)->no1)
#define FEA2          (((volatile __near __bitf_T *)0x2F0)->no2)
#define FEA3          (((volatile __near __bitf_T *)0x2F0)->no3)
#define FEA4          (((volatile __near __bitf_T *)0x2F0)->no4)
#define FEA5          (((volatile __near __bitf_T *)0x2F0)->no5)
#define CRC0EN        (((volatile __near __bitf_T *)0x2F0)->no7)
#define PGCRCL        (*(volatile __near unsigned short *)0x2F2)
#define CRCD          (*(volatile __near unsigned short *)0x2FA)
#define PDPROCON      (*(volatile __near unsigned short *)0x400)
#define PDPROSTA_LW   (*(volatile __near unsigned short *)0x404)
#define PDPROSTA_HW   (*(volatile __near unsigned short *)0x406)
#define PDPROINT_LW   (*(volatile __near unsigned short *)0x408)
#define PDPROINT_HW   (*(volatile __near unsigned short *)0x40A)
#define PDPROMIS_LW   (*(volatile __near unsigned short *)0x40C)
#define PDPROMIS_HW   (*(volatile __near unsigned short *)0x40E)
#define PDMSGHEA_LW   (*(volatile __near unsigned short *)0x410)
#define PDMSGHEA_HW   (*(volatile __near unsigned short *)0x412)
#define PDMSGDAT1_LW  (*(volatile __near unsigned short *)0x414)
#define PDMSGDAT1_HW  (*(volatile __near unsigned short *)0x416)
#define PDMSGDAT2_LW  (*(volatile __near unsigned short *)0x418)
#define PDMSGDAT2_HW  (*(volatile __near unsigned short *)0x41A)
#define PDMSGDAT3_LW  (*(volatile __near unsigned short *)0x41C)
#define PDMSGDAT3_HW  (*(volatile __near unsigned short *)0x41E)
#define PDMSGDAT4_LW  (*(volatile __near unsigned short *)0x420)
#define PDMSGDAT4_HW  (*(volatile __near unsigned short *)0x422)
#define PDMSGDAT5_LW  (*(volatile __near unsigned short *)0x424)
#define PDMSGDAT5_HW  (*(volatile __near unsigned short *)0x426)
#define PDMSGDAT6_LW  (*(volatile __near unsigned short *)0x428)
#define PDMSGDAT6_HW  (*(volatile __near unsigned short *)0x42A)
#define PDMSGDAT7_LW  (*(volatile __near unsigned short *)0x42C)
#define PDMSGDAT7_HW  (*(volatile __near unsigned short *)0x42E)
#define PDEMSGDAT_LW  (*(volatile __near unsigned short *)0x430)
#define PDEMSGDAT_HW  (*(volatile __near unsigned short *)0x432)
#define PDPROSET_LW   (*(volatile __near unsigned short *)0x434)
#define PDPROSET_HW   (*(volatile __near unsigned short *)0x436)
#define PDPHYSET1_LW  (*(volatile __near unsigned short *)0x438)
#define PDPHYSET1_HW  (*(volatile __near unsigned short *)0x43A)
#define PDPHYSET2_LW  (*(volatile __near unsigned short *)0x43C)
#define PDPHYSET2_HW  (*(volatile __near unsigned short *)0x43E)
#define PDPHYSET3_LW  (*(volatile __near unsigned short *)0x440)
#define PDPHYSET3_HW  (*(volatile __near unsigned short *)0x442)
#define SMBMCON       (*(volatile __near unsigned short *)0x500)
#define SMBMSTA       (*(volatile __near unsigned short *)0x504)
#define SMBMINT       (*(volatile __near unsigned short *)0x508)
#define SMBMADD       (*(volatile __near unsigned short *)0x50C)
#define SMBMCOM       (*(volatile __near unsigned short *)0x510)
#define SMBMDAT0_LW   (*(volatile __near unsigned short *)0x514)
#define SMBMDAT0_HW   (*(volatile __near unsigned short *)0x516)
#define SMBMDAT1_LW   (*(volatile __near unsigned short *)0x518)
#define SMBMDAT1_HW   (*(volatile __near unsigned short *)0x51A)
#define SMBMDAT2_LW   (*(volatile __near unsigned short *)0x51C)
#define SMBMDAT2_HW   (*(volatile __near unsigned short *)0x51E)
#define SMBMDAT3_LW   (*(volatile __near unsigned short *)0x520)
#define SMBMDAT3_HW   (*(volatile __near unsigned short *)0x522)
#define SMBMDAT4_LW   (*(volatile __near unsigned short *)0x524)
#define SMBMDAT4_HW   (*(volatile __near unsigned short *)0x526)
#define SMBMDAT5_LW   (*(volatile __near unsigned short *)0x528)
#define SMBMDAT5_HW   (*(volatile __near unsigned short *)0x52A)
#define SMBMDAT6_LW   (*(volatile __near unsigned short *)0x52C)
#define SMBMDAT6_HW   (*(volatile __near unsigned short *)0x52E)
#define SMBMDAT7_LW   (*(volatile __near unsigned short *)0x530)
#define SMBMDAT7_HW   (*(volatile __near unsigned short *)0x532)
#define SKT_CNT1_LW   (*(volatile __near unsigned short *)0x580)
#define SKT_CNT1_HW   (*(volatile __near unsigned short *)0x582)
#define SKT_CNT2_LW   (*(volatile __near unsigned short *)0x584)
#define SKT_CNT2_HW   (*(volatile __near unsigned short *)0x586)
#define SKT_STAT      (*(volatile __near unsigned short *)0x588)
#define SKT_INTEN     (*(volatile __near unsigned short *)0x58A)
#define SKT_MON1_LW   (*(volatile __near unsigned short *)0x58C)
#define SKT_MON1_HW   (*(volatile __near unsigned short *)0x58E)
#define SKT_MON2_LW   (*(volatile __near unsigned short *)0x590)
#define SKT_MON2_HW   (*(volatile __near unsigned short *)0x592)
#define SCNT_MODE1_LW (*(volatile __near unsigned short *)0x594)
#define SCNT_MODE1_HW (*(volatile __near unsigned short *)0x596)
#define SCNT_MODE2_LW (*(volatile __near unsigned short *)0x598)
#define SCNT_MODE2_HW (*(volatile __near unsigned short *)0x59A)
#define SCNT_MODE3_LW (*(volatile __near unsigned short *)0x59C)
#define SCNT_MODE3_HW (*(volatile __near unsigned short *)0x59E)
#define SCNT_MODE4_LW (*(volatile __near unsigned short *)0x5A0)
#define SCNT_MODE4_HW (*(volatile __near unsigned short *)0x5A2)
#define SCNT_PWRCON   (*(volatile __near unsigned short *)0x5A4)
#define SCNT_STOP_LW  (*(volatile __near unsigned short *)0x5A8)
#define SCNT_STOP_HW  (*(volatile __near unsigned short *)0x5AA)
#define CCTMC         (*(volatile __near unsigned short *)0x5F0)
#define ITRIM_REG     (*(volatile __near unsigned short *)0x5F4)
#define VTRIM_REG     (*(volatile __near unsigned short *)0x5F6)
#define SMBSCON       (*(volatile __near unsigned short *)0x600)
#define SMBSSTA       (*(volatile __near unsigned short *)0x604)
#define SMBSINT       (*(volatile __near unsigned short *)0x608)
#define SMBSADD       (*(volatile __near unsigned short *)0x60C)
#define SMBSRXCOM     (*(volatile __near unsigned short *)0x610)
#define SMBSASTA      (*(volatile __near unsigned short *)0x614)
#define SMBSSTA1_LW   (*(volatile __near unsigned short *)0x618)
#define SMBSSTA1_HW   (*(volatile __near unsigned short *)0x61A)
#define SMBSSTA2_LW   (*(volatile __near unsigned short *)0x61C)
#define SMBSSTA2_HW   (*(volatile __near unsigned short *)0x61E)
#define SMBSSTA3_LW   (*(volatile __near unsigned short *)0x620)
#define SMBSSTA3_HW   (*(volatile __near unsigned short *)0x622)
#define SMBSSTA4_LW   (*(volatile __near unsigned short *)0x624)
#define SMBSSTA4_HW   (*(volatile __near unsigned short *)0x626)
#define SMBSCOM       (*(volatile __near unsigned short *)0x628)
#define SMBSCONF1     (*(volatile __near unsigned short *)0x62C)
#define SMBSCONF2     (*(volatile __near unsigned short *)0x630)
#define SMBSDEVCAP    (*(volatile __near unsigned short *)0x634)
#define SMBSVENCOM    (*(volatile __near unsigned short *)0x638)
#define SMBSVENSTA_LW (*(volatile __near unsigned short *)0x63C)
#define SMBSVENSTA_HW (*(volatile __near unsigned short *)0x63E)
#define SMBSOBJ1_LW   (*(volatile __near unsigned short *)0x640)
#define SMBSOBJ1_HW   (*(volatile __near unsigned short *)0x642)
#define SMBSOBJ2_LW   (*(volatile __near unsigned short *)0x644)
#define SMBSOBJ2_HW   (*(volatile __near unsigned short *)0x646)
#define SMBSOBJ3_LW   (*(volatile __near unsigned short *)0x648)
#define SMBSOBJ3_HW   (*(volatile __near unsigned short *)0x64A)
#define SMBSOBJ4_LW   (*(volatile __near unsigned short *)0x64C)
#define SMBSOBJ4_HW   (*(volatile __near unsigned short *)0x64E)
#define SMBSOBJ5_LW   (*(volatile __near unsigned short *)0x650)
#define SMBSOBJ5_HW   (*(volatile __near unsigned short *)0x652)
#define SMBSOBJ6_LW   (*(volatile __near unsigned short *)0x654)
#define SMBSOBJ6_HW   (*(volatile __near unsigned short *)0x656)
#define SMBSOBJ7_LW   (*(volatile __near unsigned short *)0x658)
#define SMBSOBJ7_HW   (*(volatile __near unsigned short *)0x65A)
#define SMBSSCONF1    (*(volatile __near unsigned short *)0x65C)
#define SMBSSCONF2    (*(volatile __near unsigned short *)0x660)
#define SMBSSCONF3    (*(volatile __near unsigned short *)0x664)
#define SMBSAEN       (*(volatile __near unsigned short *)0x668)
#define SMBSFTYPE     (*(volatile __near unsigned short *)0x66C)
#define SMBSFREV      (*(volatile __near unsigned short *)0x670)
#define SMBSMID       (*(volatile __near unsigned short *)0x674)
#define SMBSDID       (*(volatile __near unsigned short *)0x678)
#define SMBSRID       (*(volatile __near unsigned short *)0x67C)
#define SMBSINREG     (*(volatile __near unsigned short *)0x680)
#define SMBSINDAT     (*(volatile __near unsigned short *)0x684)
#define SMBSFCON      (*(volatile __near unsigned short *)0x688)
#define SMBSHWID_LW   (*(volatile __near unsigned short *)0x68C)
#define SMBSHWID_HW   (*(volatile __near unsigned short *)0x68E)
#define SMBSPAD0_LW   (*(volatile __near unsigned short *)0x690)
#define SMBSPAD0_HW   (*(volatile __near unsigned short *)0x692)
#define SMBSPAD1_LW   (*(volatile __near unsigned short *)0x694)
#define SMBSPAD1_HW   (*(volatile __near unsigned short *)0x696)
#define P1            (*(volatile __near unsigned char  *)0xFF01)
#define P1_bit        (*(volatile __near __bitf_T *)0xFF01)
#define P2            (*(volatile __near unsigned char  *)0xFF02)
#define P2_bit        (*(volatile __near __bitf_T *)0xFF02)
#define P3            (*(volatile __near unsigned char  *)0xFF03)
#define P3_bit        (*(volatile __near __bitf_T *)0xFF03)
#define P4            (*(volatile __near unsigned char  *)0xFF04)
#define P4_bit        (*(volatile __near __bitf_T *)0xFF04)
#define P5            (*(volatile __near unsigned char  *)0xFF05)
#define P5_bit        (*(volatile __near __bitf_T *)0xFF05)
#define P6            (*(volatile __near unsigned char  *)0xFF06)
#define P6_bit        (*(volatile __near __bitf_T *)0xFF06)
#define P7            (*(volatile __near unsigned char  *)0xFF07)
#define P7_bit        (*(volatile __near __bitf_T *)0xFF07)
#define P8            (*(volatile __near unsigned char  *)0xFF08)
#define P8_bit        (*(volatile __near __bitf_T *)0xFF08)
#define P12           (*(volatile __near unsigned char  *)0xFF0C)
#define P12_bit       (*(volatile __near __bitf_T *)0xFF0C)
#define P13           (*(volatile __near unsigned char  *)0xFF0D)
#define P13_bit       (*(volatile __near __bitf_T *)0xFF0D)
#define SDR00         (*(volatile __near unsigned short *)0xFF10)
#define SIO00         (*(volatile __near unsigned char  *)0xFF10)
#define TXD0          (*(volatile __near unsigned char  *)0xFF10)
#define SDR01         (*(volatile __near unsigned short *)0xFF12)
#define RXD0          (*(volatile __near unsigned char  *)0xFF12)
#define SIO01         (*(volatile __near unsigned char  *)0xFF12)
#define TDR00         (*(volatile __near unsigned short *)0xFF18)
#define TDR01         (*(volatile __near unsigned short *)0xFF1A)
#define TDR01L        (*(volatile __near unsigned char  *)0xFF1A)
#define TDR01H        (*(volatile __near unsigned char  *)0xFF1B)
#define ADCR          (*(volatile __near unsigned short *)0xFF1E)
#define ADCRH         (*(volatile __near unsigned char  *)0xFF1F)
#define PM1           (*(volatile __near unsigned char  *)0xFF21)
#define PM1_bit       (*(volatile __near __bitf_T *)0xFF21)
#define PM2           (*(volatile __near unsigned char  *)0xFF22)
#define PM2_bit       (*(volatile __near __bitf_T *)0xFF22)
#define PM3           (*(volatile __near unsigned char  *)0xFF23)
#define PM3_bit       (*(volatile __near __bitf_T *)0xFF23)
#define PM4           (*(volatile __near unsigned char  *)0xFF24)
#define PM4_bit       (*(volatile __near __bitf_T *)0xFF24)
#define PM5           (*(volatile __near unsigned char  *)0xFF25)
#define PM5_bit       (*(volatile __near __bitf_T *)0xFF25)
#define PM6           (*(volatile __near unsigned char  *)0xFF26)
#define PM6_bit       (*(volatile __near __bitf_T *)0xFF26)
#define PM7           (*(volatile __near unsigned char  *)0xFF27)
#define PM7_bit       (*(volatile __near __bitf_T *)0xFF27)
#define PM8           (*(volatile __near unsigned char  *)0xFF28)
#define PM8_bit       (*(volatile __near __bitf_T *)0xFF28)
#define ADM0          (*(volatile __near unsigned char  *)0xFF30)
#define ADM0_bit      (*(volatile __near __bitf_T *)0xFF30)
#define ADCE          (((volatile __near __bitf_T *)0xFF30)->no0)
#define ADCS          (((volatile __near __bitf_T *)0xFF30)->no7)
#define ADS           (*(volatile __near unsigned char  *)0xFF31)
#define ADS_bit       (*(volatile __near __bitf_T *)0xFF31)
#define ADM1          (*(volatile __near unsigned char  *)0xFF32)
#define ADM1_bit      (*(volatile __near __bitf_T *)0xFF32)
#define EGP0          (*(volatile __near unsigned char  *)0xFF38)
#define EGP0_bit      (*(volatile __near __bitf_T *)0xFF38)
#define EGN0          (*(volatile __near unsigned char  *)0xFF39)
#define EGN0_bit      (*(volatile __near __bitf_T *)0xFF39)
#define IICA0         (*(volatile __near unsigned char  *)0xFF50)
#define IICS0         (*(volatile __near unsigned char  *)0xFF51)
#define IICS0_bit     (*(volatile __near __bitf_T *)0xFF51)
#define SPD0          (((volatile __near __bitf_T *)0xFF51)->no0)
#define STD0          (((volatile __near __bitf_T *)0xFF51)->no1)
#define ACKD0         (((volatile __near __bitf_T *)0xFF51)->no2)
#define TRC0          (((volatile __near __bitf_T *)0xFF51)->no3)
#define COI0          (((volatile __near __bitf_T *)0xFF51)->no4)
#define EXC0          (((volatile __near __bitf_T *)0xFF51)->no5)
#define ALD0          (((volatile __near __bitf_T *)0xFF51)->no6)
#define MSTS0         (((volatile __near __bitf_T *)0xFF51)->no7)
#define IICF0         (*(volatile __near unsigned char  *)0xFF52)
#define IICF0_bit     (*(volatile __near __bitf_T *)0xFF52)
#define IICRSV0       (((volatile __near __bitf_T *)0xFF52)->no0)
#define STCEN0        (((volatile __near __bitf_T *)0xFF52)->no1)
#define IICBSY0       (((volatile __near __bitf_T *)0xFF52)->no6)
#define STCF0         (((volatile __near __bitf_T *)0xFF52)->no7)
#define TDR02         (*(volatile __near unsigned short *)0xFF64)
#define TDR03         (*(volatile __near unsigned short *)0xFF66)
#define TDR03L        (*(volatile __near unsigned char  *)0xFF66)
#define TDR03H        (*(volatile __near unsigned char  *)0xFF67)
#define ITMC          (*(volatile __near unsigned short *)0xFF90)
#define CMC           (*(volatile __near unsigned char  *)0xFFA0)
#define CSC           (*(volatile __near unsigned char  *)0xFFA1)
#define CSC_bit       (*(volatile __near __bitf_T *)0xFFA1)
#define HIOSTOP       (((volatile __near __bitf_T *)0xFFA1)->no0)
#define MIOEN         (((volatile __near __bitf_T *)0xFFA1)->no1)
#define XTWKUP        (((volatile __near __bitf_T *)0xFFA1)->no5)
#define XTSTOP        (((volatile __near __bitf_T *)0xFFA1)->no6)
#define MSTOP         (((volatile __near __bitf_T *)0xFFA1)->no7)
#define OSTC          (*(volatile __near unsigned char  *)0xFFA2)
#define OSTC_bit      (*(volatile __near __bitf_T *)0xFFA2)
#define OSTS          (*(volatile __near unsigned char  *)0xFFA3)
#define CKC           (*(volatile __near unsigned char  *)0xFFA4)
#define CKC_bit       (*(volatile __near __bitf_T *)0xFFA4)
#define MCM1          (((volatile __near __bitf_T *)0xFFA4)->no0)
#define MCS1          (((volatile __near __bitf_T *)0xFFA4)->no1)
#define MCM0          (((volatile __near __bitf_T *)0xFFA4)->no4)
#define MCS           (((volatile __near __bitf_T *)0xFFA4)->no5)
#define CSS           (((volatile __near __bitf_T *)0xFFA4)->no6)
#define CLS           (((volatile __near __bitf_T *)0xFFA4)->no7)
#define CKS0          (*(volatile __near unsigned char  *)0xFFA5)
#define CKS0_bit      (*(volatile __near __bitf_T *)0xFFA5)
#define PCLOE0        (((volatile __near __bitf_T *)0xFFA5)->no7)
#define CKS1          (*(volatile __near unsigned char  *)0xFFA6)
#define CKS1_bit      (*(volatile __near __bitf_T *)0xFFA6)
#define PCLOE1        (((volatile __near __bitf_T *)0xFFA6)->no7)
#define CKSEL         (*(volatile __near unsigned char  *)0xFFA7)
#define CKSEL_bit     (*(volatile __near __bitf_T *)0xFFA7)
#define SELLOSC       (((volatile __near __bitf_T *)0xFFA7)->no0)
#define RESF          (*(volatile __near unsigned char  *)0xFFA8)
#define LVIM          (*(volatile __near unsigned char  *)0xFFA9)
#define LVIM_bit      (*(volatile __near __bitf_T *)0xFFA9)
#define LVIF          (((volatile __near __bitf_T *)0xFFA9)->no0)
#define LVIOMSK       (((volatile __near __bitf_T *)0xFFA9)->no1)
#define LVISEN        (((volatile __near __bitf_T *)0xFFA9)->no7)
#define LVIS          (*(volatile __near unsigned char  *)0xFFAA)
#define LVIS_bit      (*(volatile __near __bitf_T *)0xFFAA)
#define LVILV         (((volatile __near __bitf_T *)0xFFAA)->no0)
#define LVIMD         (((volatile __near __bitf_T *)0xFFAA)->no7)
#define WDTE          (*(volatile __near unsigned char  *)0xFFAB)
#define CRCIN         (*(volatile __near unsigned char  *)0xFFAC)
#define IF2           (*(volatile __near unsigned short *)0xFFD0)
#define IF2L          (*(volatile __near unsigned char  *)0xFFD0)
#define IF2L_bit      (*(volatile __near __bitf_T *)0xFFD0)
#define IF2H          (*(volatile __near unsigned char  *)0xFFD1)
#define IF2H_bit      (*(volatile __near __bitf_T *)0xFFD1)
#define PIF7          (((volatile __near __bitf_T *)0xFFD0)->no4)
#define IICAIF0       (((volatile __near __bitf_T *)0xFFD0)->no5)
#define FLIF          (((volatile __near __bitf_T *)0xFFD1)->no7)
#define MK2           (*(volatile __near unsigned short *)0xFFD4)
#define MK2L          (*(volatile __near unsigned char  *)0xFFD4)
#define MK2L_bit      (*(volatile __near __bitf_T *)0xFFD4)
#define MK2H          (*(volatile __near unsigned char  *)0xFFD5)
#define MK2H_bit      (*(volatile __near __bitf_T *)0xFFD5)
#define PMK7          (((volatile __near __bitf_T *)0xFFD4)->no4)
#define IICAMK0       (((volatile __near __bitf_T *)0xFFD4)->no5)
#define FLMK          (((volatile __near __bitf_T *)0xFFD5)->no7)
#define PR02          (*(volatile __near unsigned short *)0xFFD8)
#define PR02L         (*(volatile __near unsigned char  *)0xFFD8)
#define PR02L_bit     (*(volatile __near __bitf_T *)0xFFD8)
#define PR02H         (*(volatile __near unsigned char  *)0xFFD9)
#define PR02H_bit     (*(volatile __near __bitf_T *)0xFFD9)
#define PPR07         (((volatile __near __bitf_T *)0xFFD8)->no4)
#define IICAPR00      (((volatile __near __bitf_T *)0xFFD8)->no5)
#define FLPR0         (((volatile __near __bitf_T *)0xFFD9)->no7)
#define PR12          (*(volatile __near unsigned short *)0xFFDC)
#define PR12L         (*(volatile __near unsigned char  *)0xFFDC)
#define PR12L_bit     (*(volatile __near __bitf_T *)0xFFDC)
#define PR12H         (*(volatile __near unsigned char  *)0xFFDD)
#define PR12H_bit     (*(volatile __near __bitf_T *)0xFFDD)
#define PPR17         (((volatile __near __bitf_T *)0xFFDC)->no4)
#define IICAPR10      (((volatile __near __bitf_T *)0xFFDC)->no5)
#define FLPR1         (((volatile __near __bitf_T *)0xFFDD)->no7)
#define IF0           (*(volatile __near unsigned short *)0xFFE0)
#define IF0L          (*(volatile __near unsigned char  *)0xFFE0)
#define IF0L_bit      (*(volatile __near __bitf_T *)0xFFE0)
#define IF0H          (*(volatile __near unsigned char  *)0xFFE1)
#define IF0H_bit      (*(volatile __near __bitf_T *)0xFFE1)
#define SROIF         (((volatile __near __bitf_T *)0xFFE0)->no0)
#define WDTIIF        (((volatile __near __bitf_T *)0xFFE0)->no0)
#define LVIIF         (((volatile __near __bitf_T *)0xFFE0)->no1)
#define PIF0          (((volatile __near __bitf_T *)0xFFE0)->no2)
#define PIF1          (((volatile __near __bitf_T *)0xFFE0)->no3)
#define PIF2          (((volatile __near __bitf_T *)0xFFE0)->no4)
#define PIF3          (((volatile __near __bitf_T *)0xFFE0)->no5)
#define PIF4          (((volatile __near __bitf_T *)0xFFE0)->no6)
#define PIF5          (((volatile __near __bitf_T *)0xFFE0)->no7)
#define PIF6          (((volatile __near __bitf_T *)0xFFE1)->no0)
#define CSIIF00       (((volatile __near __bitf_T *)0xFFE1)->no1)
#define IIIF00        (((volatile __near __bitf_T *)0xFFE1)->no1)
#define STIF0         (((volatile __near __bitf_T *)0xFFE1)->no1)
#define CSIIF01       (((volatile __near __bitf_T *)0xFFE1)->no2)
#define IIIF01        (((volatile __near __bitf_T *)0xFFE1)->no2)
#define SRIF0         (((volatile __near __bitf_T *)0xFFE1)->no2)
#define SREIF0        (((volatile __near __bitf_T *)0xFFE1)->no5)
#define TMIF00        (((volatile __near __bitf_T *)0xFFE1)->no6)
#define IF1           (*(volatile __near unsigned short *)0xFFE2)
#define IF1L          (*(volatile __near unsigned char  *)0xFFE2)
#define IF1L_bit      (*(volatile __near __bitf_T *)0xFFE2)
#define IF1H          (*(volatile __near unsigned char  *)0xFFE3)
#define IF1H_bit      (*(volatile __near __bitf_T *)0xFFE3)
#define TMIF01H       (((volatile __near __bitf_T *)0xFFE2)->no1)
#define TMIF03H       (((volatile __near __bitf_T *)0xFFE2)->no2)
#define TMIF01        (((volatile __near __bitf_T *)0xFFE2)->no3)
#define TMIF02        (((volatile __near __bitf_T *)0xFFE2)->no4)
#define TMIF03        (((volatile __near __bitf_T *)0xFFE2)->no5)
#define ADIF          (((volatile __near __bitf_T *)0xFFE3)->no0)
#define TMKAIF        (((volatile __near __bitf_T *)0xFFE3)->no2)
#define PDCTRLIF      (((volatile __near __bitf_T *)0xFFE3)->no4)
#define SMBMSTIF      (((volatile __near __bitf_T *)0xFFE3)->no5)
#define SMBSLVIF      (((volatile __near __bitf_T *)0xFFE3)->no6)
#define TCSCNTIF      (((volatile __near __bitf_T *)0xFFE3)->no7)
#define MK0           (*(volatile __near unsigned short *)0xFFE4)
#define MK0L          (*(volatile __near unsigned char  *)0xFFE4)
#define MK0L_bit      (*(volatile __near __bitf_T *)0xFFE4)
#define MK0H          (*(volatile __near unsigned char  *)0xFFE5)
#define MK0H_bit      (*(volatile __near __bitf_T *)0xFFE5)
#define SROMK         (((volatile __near __bitf_T *)0xFFE4)->no0)
#define WDTIMK        (((volatile __near __bitf_T *)0xFFE4)->no0)
#define LVIMK         (((volatile __near __bitf_T *)0xFFE4)->no1)
#define PMK0          (((volatile __near __bitf_T *)0xFFE4)->no2)
#define PMK1          (((volatile __near __bitf_T *)0xFFE4)->no3)
#define PMK2          (((volatile __near __bitf_T *)0xFFE4)->no4)
#define PMK3          (((volatile __near __bitf_T *)0xFFE4)->no5)
#define PMK4          (((volatile __near __bitf_T *)0xFFE4)->no6)
#define PMK5          (((volatile __near __bitf_T *)0xFFE4)->no7)
#define PMK6          (((volatile __near __bitf_T *)0xFFE5)->no0)
#define CSIMK00       (((volatile __near __bitf_T *)0xFFE5)->no1)
#define IIMK00        (((volatile __near __bitf_T *)0xFFE5)->no1)
#define STMK0         (((volatile __near __bitf_T *)0xFFE5)->no1)
#define CSIMK01       (((volatile __near __bitf_T *)0xFFE5)->no2)
#define IIMK01        (((volatile __near __bitf_T *)0xFFE5)->no2)
#define SRMK0         (((volatile __near __bitf_T *)0xFFE5)->no2)
#define SREMK0        (((volatile __near __bitf_T *)0xFFE5)->no5)
#define TMMK00        (((volatile __near __bitf_T *)0xFFE5)->no6)
#define MK1           (*(volatile __near unsigned short *)0xFFE6)
#define MK1L          (*(volatile __near unsigned char  *)0xFFE6)
#define MK1L_bit      (*(volatile __near __bitf_T *)0xFFE6)
#define MK1H          (*(volatile __near unsigned char  *)0xFFE7)
#define MK1H_bit      (*(volatile __near __bitf_T *)0xFFE7)
#define TMMK01H       (((volatile __near __bitf_T *)0xFFE6)->no1)
#define TMMK03H       (((volatile __near __bitf_T *)0xFFE6)->no2)
#define TMMK01        (((volatile __near __bitf_T *)0xFFE6)->no3)
#define TMMK02        (((volatile __near __bitf_T *)0xFFE6)->no4)
#define TMMK03        (((volatile __near __bitf_T *)0xFFE6)->no5)
#define ADMK          (((volatile __near __bitf_T *)0xFFE7)->no0)
#define TMKAMK        (((volatile __near __bitf_T *)0xFFE7)->no2)
#define PDCTRLMK      (((volatile __near __bitf_T *)0xFFE7)->no4)
#define SMBMSTMK      (((volatile __near __bitf_T *)0xFFE7)->no5)
#define SMBSLVMK      (((volatile __near __bitf_T *)0xFFE7)->no6)
#define TCSCNTMK      (((volatile __near __bitf_T *)0xFFE7)->no7)
#define PR00          (*(volatile __near unsigned short *)0xFFE8)
#define PR00L         (*(volatile __near unsigned char  *)0xFFE8)
#define PR00L_bit     (*(volatile __near __bitf_T *)0xFFE8)
#define PR00H         (*(volatile __near unsigned char  *)0xFFE9)
#define PR00H_bit     (*(volatile __near __bitf_T *)0xFFE9)
#define SROPR0        (((volatile __near __bitf_T *)0xFFE8)->no0)
#define WDTIPR0       (((volatile __near __bitf_T *)0xFFE8)->no0)
#define LVIPR0        (((volatile __near __bitf_T *)0xFFE8)->no1)
#define PPR00         (((volatile __near __bitf_T *)0xFFE8)->no2)
#define PPR01         (((volatile __near __bitf_T *)0xFFE8)->no3)
#define PPR02         (((volatile __near __bitf_T *)0xFFE8)->no4)
#define PPR03         (((volatile __near __bitf_T *)0xFFE8)->no5)
#define PPR04         (((volatile __near __bitf_T *)0xFFE8)->no6)
#define PPR05         (((volatile __near __bitf_T *)0xFFE8)->no7)
#define PPR06         (((volatile __near __bitf_T *)0xFFE9)->no0)
#define CSIPR000      (((volatile __near __bitf_T *)0xFFE9)->no1)
#define IIPR000       (((volatile __near __bitf_T *)0xFFE9)->no1)
#define STPR00        (((volatile __near __bitf_T *)0xFFE9)->no1)
#define CSIPR001      (((volatile __near __bitf_T *)0xFFE9)->no2)
#define IIPR001       (((volatile __near __bitf_T *)0xFFE9)->no2)
#define SRPR00        (((volatile __near __bitf_T *)0xFFE9)->no2)
#define SREPR00       (((volatile __near __bitf_T *)0xFFE9)->no5)
#define TMPR000       (((volatile __near __bitf_T *)0xFFE9)->no6)
#define PR01          (*(volatile __near unsigned short *)0xFFEA)
#define PR01L         (*(volatile __near unsigned char  *)0xFFEA)
#define PR01L_bit     (*(volatile __near __bitf_T *)0xFFEA)
#define PR01H         (*(volatile __near unsigned char  *)0xFFEB)
#define PR01H_bit     (*(volatile __near __bitf_T *)0xFFEB)
#define TMPR001H      (((volatile __near __bitf_T *)0xFFEA)->no1)
#define TMPR003H      (((volatile __near __bitf_T *)0xFFEA)->no2)
#define TMPR001       (((volatile __near __bitf_T *)0xFFEA)->no3)
#define TMPR002       (((volatile __near __bitf_T *)0xFFEA)->no4)
#define TMPR003       (((volatile __near __bitf_T *)0xFFEA)->no5)
#define ADPR0         (((volatile __near __bitf_T *)0xFFEB)->no0)
#define TMKAPR0       (((volatile __near __bitf_T *)0xFFEB)->no2)
#define PDCTRLPR0     (((volatile __near __bitf_T *)0xFFEB)->no4)
#define SMBMSTPR0     (((volatile __near __bitf_T *)0xFFEB)->no5)
#define SMBSLVPR0     (((volatile __near __bitf_T *)0xFFEB)->no6)
#define TCSCNTPR0     (((volatile __near __bitf_T *)0xFFEB)->no7)
#define PR10          (*(volatile __near unsigned short *)0xFFEC)
#define PR10L         (*(volatile __near unsigned char  *)0xFFEC)
#define PR10L_bit     (*(volatile __near __bitf_T *)0xFFEC)
#define PR10H         (*(volatile __near unsigned char  *)0xFFED)
#define PR10H_bit     (*(volatile __near __bitf_T *)0xFFED)
#define SROPR1        (((volatile __near __bitf_T *)0xFFEC)->no0)
#define WDTIPR1       (((volatile __near __bitf_T *)0xFFEC)->no0)
#define LVIPR1        (((volatile __near __bitf_T *)0xFFEC)->no1)
#define PPR10         (((volatile __near __bitf_T *)0xFFEC)->no2)
#define PPR11         (((volatile __near __bitf_T *)0xFFEC)->no3)
#define PPR12         (((volatile __near __bitf_T *)0xFFEC)->no4)
#define PPR13         (((volatile __near __bitf_T *)0xFFEC)->no5)
#define PPR14         (((volatile __near __bitf_T *)0xFFEC)->no6)
#define PPR15         (((volatile __near __bitf_T *)0xFFEC)->no7)
#define PPR16         (((volatile __near __bitf_T *)0xFFED)->no0)
#define CSIPR100      (((volatile __near __bitf_T *)0xFFED)->no1)
#define IIPR100       (((volatile __near __bitf_T *)0xFFED)->no1)
#define STPR10        (((volatile __near __bitf_T *)0xFFED)->no1)
#define CSIPR101      (((volatile __near __bitf_T *)0xFFED)->no2)
#define IIPR101       (((volatile __near __bitf_T *)0xFFED)->no2)
#define SRPR10        (((volatile __near __bitf_T *)0xFFED)->no2)
#define SREPR10       (((volatile __near __bitf_T *)0xFFED)->no5)
#define TMPR100       (((volatile __near __bitf_T *)0xFFED)->no6)
#define PR11          (*(volatile __near unsigned short *)0xFFEE)
#define PR11L         (*(volatile __near unsigned char  *)0xFFEE)
#define PR11L_bit     (*(volatile __near __bitf_T *)0xFFEE)
#define PR11H         (*(volatile __near unsigned char  *)0xFFEF)
#define PR11H_bit     (*(volatile __near __bitf_T *)0xFFEF)
#define TMPR101H      (((volatile __near __bitf_T *)0xFFEE)->no1)
#define TMPR103H      (((volatile __near __bitf_T *)0xFFEE)->no2)
#define TMPR101       (((volatile __near __bitf_T *)0xFFEE)->no3)
#define TMPR102       (((volatile __near __bitf_T *)0xFFEE)->no4)
#define TMPR103       (((volatile __near __bitf_T *)0xFFEE)->no5)
#define ADPR1         (((volatile __near __bitf_T *)0xFFEF)->no0)
#define TMKAPR1       (((volatile __near __bitf_T *)0xFFEF)->no2)
#define PDCTRLPR1     (((volatile __near __bitf_T *)0xFFEF)->no4)
#define SMBMSTPR1     (((volatile __near __bitf_T *)0xFFEF)->no5)
#define SMBSLVPR1     (((volatile __near __bitf_T *)0xFFEF)->no6)
#define TCSCNTPR1     (((volatile __near __bitf_T *)0xFFEF)->no7)
#define MACRL         (*(volatile __near unsigned short *)0xFFF0)
#define MACRH         (*(volatile __near unsigned short *)0xFFF2)
#define PMC           (*(volatile __near unsigned char  *)0xFFFE)
#define PMC_bit       (*(volatile __near __bitf_T *)0xFFFE)


#define INTSRO                          0x0004
#define INTWDTI                         0x0004
#define INTLVI                          0x0006
#define INTP0                           0x0008
#define INTP1                           0x000A
#define INTP2                           0x000C
#define INTP3                           0x000E
#define INTP4                           0x0010
#define INTP5                           0x0012
#define INTP6                           0x0014
#define INTCSI00                        0x0016
#define INTIIC00                        0x0016
#define INTST0                          0x0016
#define INTCSI01                        0x0018
#define INTIIC01                        0x0018
#define INTSR0                          0x0018
#define INTSRE0                         0x001E
#define INTTM00                         0x0020
#define INTTM01H                        0x0026
#define INTTM03H                        0x0028
#define INTTM01                         0x002A
#define INTTM02                         0x002C
#define INTTM03                         0x002E
#define INTAD                           0x0034
#define INTIT                           0x0038
#define INTPDCTRL                       0x003C
#define INTSMBMST                       0x003E
#define INTSMBSLV                       0x0040
#define INTTCSCNT                       0x0042
#define INTP7                           0x004C
#define INTIICA0                        0x004E
#define INTFL                           0x0062

#endif
